import React, { useRef } from "react";
import { useFrame } from "@react-three/fiber";
import { Box, useGLTF } from "@react-three/drei";
import { MeshPhysicalMaterial } from "three";
import { MeshBasicMaterial } from "three";
import { MeshPhongMaterial } from "three";

// Auto-generated by: https://github.com/pmndrs/gltfjsx
export default function Model({ url, ...props }) {
  const group = useRef();
  useFrame((state) => {
    group.current.children.forEach((child, index) => {
      child.position.y += Math.sin(index * 1000 + state.clock.elapsedTime) / 50;
      child.rotation.x +=
        (Math.sin(index * 1000 + state.clock.elapsedTime) * Math.PI) / 2000;
      child.rotation.y +=
        (Math.cos(index * 1000 + state.clock.elapsedTime) * Math.PI) / 3000;
      child.rotation.z +=
        (Math.sin(index * 1000 + state.clock.elapsedTime) * Math.PI) / 4000;
    });
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <Box
        scale={10}
        position={[0.8, -10.96, 2.16]}
        rotation={[1.76, 0.07, -0.19]}
      >
        <meshPhongMaterial attach="material" color="#6b6b6b" opacity={0.5} transparent/>
      </Box>
      <Box
        scale={10}
        position={[19.9, -12.6, -17.01]}
        rotation={[1.26, 0.91, -1.86]}
      >
        <meshPhongMaterial attach="material" color="#ffffff" />
      </Box>
      <Box
        scale={10}
        position={[20.22, 1.99, 4.03]}
        rotation={[1.55, 0.32, -0.76]}
      >
        <meshPhongMaterial attach="material" color="#ffffff" />
      </Box>
      <Box
        scale={10}
        position={[-21.4, -14.96, -13.21]}
        rotation={[1.83, -0.23, 0.91]}
      >
        <meshPhongMaterial attach="material" color="#ffffff" />
      </Box>
    </group>
  );
}
